a, b = input().split()
print(a + b)
print(type(a))
print(type(b))
c, d = map(int, input().split())
print(c + d)
print(type(c))
print(type(d))
e, f = map(float, input().split())
print(e+f)
print(type(e))
print(type(f))
